const bcrypt = require("bcrypt")
const moment = require("moment")

const { database } = require("../../database/database-client")

const bcryptSaltRounds = 10

const signup = async (req, res) => {
    const { fullName, phone, email } = req.body

    // existingUser
    // if (existingUser) {
    //     return res
    //         .status(400)
    //         .json({ error: ["user already exist with this email id"] })
    // }

    const autoGeneratedPassword = Math.random().toString(36).substring(2, 12)

    await database.user.insertOne({
        username: email,
        password: await bcrypt.hash(autoGeneratedPassword, bcryptSaltRounds),
        fullName: fullName,
        phone: phone,
        email: email,
        createdAt: moment().toISOString(true),
        updatedAt: moment().toISOString(true),
    })

    return res.json({
        status: true,
        data: {
            username: email,
            password: autoGeneratedPassword,
            fullName: fullName,
            phone: phone,
            email: email,
        },
    })
}

const getUser = async (req, res) => {
    const username = req.params.username

    const user = await database.user.findOne({ username })

    if (!user) {
        return res.status(400).json({ error: ["user does not exist"] })
    }

    user.password = "**********"

    return res.json({
        status: true,
        data: user,
    })
}

module.exports = { signup, getUser }
