@token = eyJhbGciOiJSUzUxMiJ9.eyJqd3RQYXlsb2FkIjp7ImlzcyI6IkVTRy1DT0xMRUNUSU9OUyIsInVzZXJuYW1lIjoicHJpdGh2aUBnbWFpbC5jb20ifSwiaWF0IjoxNjgwNDU1MjAzLCJleHAiOjE2ODA0OTg0MDMsImF1ZCI6ImF1ZGllbmNlIn0.AQFeKdECOQP7VyDyU-YuEyvSxVU4FZsLbYRrV4PCTByGSDhCxbEBNRVbqc4nEieBQX0wOfE-HpzXrqfr2aiboCH7yBRvRWT6pW1qYvqKHMjf_h8nV2KYlnUn38WrI9tcEY0Bz2qSHVcBNL72AtxRpalPRIMWqWx3u0k7_nJJLasKeDj3QfMoW59nY_OE8duq9dSSEAEvAPT4MTMPW9Oyo0NeNvN-PmqtDHm5r-z0uKcsqMSIW7j5Bl7HbtvBVyS-vEmPgLzI5qG9dNATLPQBi5sM0wPY6MlRUtgNJrSIvS87X-EtbrkctDG-BNaYEQ7gLbvfK3_0uHUQKkafflgLJA

POST http://localhost:5000/esg-collect/login
content-type: application/json

{
    "username": "prithvi@gmail.com",
    "password": "ci4hlozhab"
}

###

POST http://localhost:5002/esg-collect/user/signup
content-type: application/json

{
    "fullName": "Prithvi Sharma",
    "phone": "9000000001",
    "email": "prithvi@gmail.com"
}

###

GET http://localhost:5000/esg-collect/user/prithvi@gmail.com
Authorization: Bearer {{token}}

###

POST http://localhost:5000/esg-collect/report/
Authorization: Bearer {{token}}
content-type: application/json

{
    "reportId": "8200dedd-848a-4645-be9a-926e4ba396ea",
    "questionId": "Q5",
    "answer": {
        "permanentEmployees": {
            "yesNo": "YES",
            "details": "My details 1"
        },
        "otherEmployees": {
            "yesNo": "no",
            "details": "My details 2"
        },
        "permanentWorkers": {
            "yesNo": "YES",
            "details": "My details 3"
        },
        "otherWorkers": {
            "yesNo": "YES",
            "details": "My details 4"
        }
    }

}

###

GET http://localhost:5000/esg-collect/report/by-report-id/3c0ae9c6-1f32-4ed7-83cc-f71f6f738477
Authorization: Bearer {{token}}

###

GET http://localhost:5000/esg-collect/report/by-username/prithvix@gmail.com
Authorization: Bearer {{token}}

###

GET http://localhost:5000/esg-collect/report/questions
Authorization: Bearer {{token}}

###